name: CI

env:
  flutter_version: '2.5.x'
  java_version: '12.x'

on:
  workflow_dispatch:
  push:


jobs:
  setup:
    runs-on: ${{ matrix.os }}

    strategy:
      
      matrix:
        os: ["ubuntu-latest"]
        include: 
        - os: ubuntu-latest
          flutter_path: /opt/hostedtoolcache/flutter
        #- os: macos-latest
        #  flutter_path: /Users/runner/hostedtoolcache/flutter
      fail-fast: false
       
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.java_version }}
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.flutter_version }}
    - name: Cache Flutter dependencies
      uses: actions/cache@v1
      with:
        path: ${{ matrix.flutter_path }}
        key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
    - name: Install dependencies
      run: flutter pub get
    
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.java_version }}
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.flutter_version }}
    - name: Cache Flutter dependencies
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
#    - run: flutter test

  android:
    needs: test
    runs-on: ubuntu-latest
    env:
      MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.java_version }}
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.flutter_version }}
    - name: Cache Flutter dependencies
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
    - run: flutter build apk
    - run: flutter build appbundle
    
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: android-release
        path: |
          build/app/outputs/flutter-apk/app-release.apk
          build/app/outputs/bundle/release/app-release.aab

  # ios:
  #   needs: test
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-java@v1
  #     with:
  #       java-version: ${{ env.java_version }}
  #   - uses: subosito/flutter-action@v1
  #     with:
  #       flutter-version: ${{ env.flutter_version }}
  #   - name: Cache Flutter dependencies
  #     uses: actions/cache@v1
  #     with:
  #       path: /Users/runner/hostedtoolcache/flutter
  #       key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
  #   - run: flutter build apk
  #   - run: flutter build ios --release --no-codesign
