on:
  workflow_dispatch:
    inputs:
      tag:
        description: "release tag"
        required: true

name: Google Playstore

env:
  appname: demogonio
  appkey: eu.molinier.demogonio

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: download
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        version: "tags/${{ github.event.inputs.tag }}"
        file: "${{ env.appname }}-${{ github.event.inputs.tag }}.aab"
        target: "release.aab"
        token: ${{ secrets.GITHUB_TOKEN }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: download
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2

    - name: Deploy to Internal
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_KEY }}
        packageName: ${{ env.appkey }}
        releaseFiles: release.aab
        track: internal