on:
  workflow_call:
    inputs:
      run-id:
        required: true
        type: string

name: Release

env:
  appname: demogonio

jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
#        uses: dawidd6/action-download-artifact@v2
#        with:
#          workflow: CI
#          run_id: ${{ inputs.run-id }}
        uses: actions/download-artifact@v2

      - name: Extract tag name
        id: tag
        uses: actions/github-script@v5
        with:
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.tag.outputs.result }}
          draft: false
          prerelease: false

      - name: Upload Release Asset (apk)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: android-release/app-release.apk
          asset_name: ${{ env.appname }}-${{ steps.tag.outputs.result }}.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Release Asset (aab)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: android-release/app-release.aab
          asset_name: ${{ env.appname }}-${{ steps.tag.outputs.result }}.aab
          asset_content_type: application/x-authorware-bin